version: '3'
services:

    nginx_app:
        image: nginx:latest
        depends_on:
            - flask_app
        volumes:
            - './nginx/nginx.conf:/etc/nginx/nginx.conf'
        ports:
            - 8090:80
        networks:
            - backend

    flask_app:
        image: jonathanyk/sessions-project:githubactions
        ports:
            - 8081:5000
        expose:
            - 5000
        networks:
            - backend

    tf:
        image: hashicorp/terraform:1.7
        volumes:
            - .:/infra
        working_dir: /infra
        environment:
            - AWS_ACCESS_KEY_ID=AKIAU6GDZGRDDL6SGDWO
            - AWS_SECRET_ACCESS_KEY=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
              #- command: ["tail", "-f", "/dev/null"]



networks:
    backend:
